# Site settings
title: 
header-img: img/home-bg.png
email: bethmschofield@gmail.com
copyright_name: Gingertonic
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: bethmichellemusic
github_username:  Gingertonic
learn_profile: Gingertonic
email_username: bethmschofield@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
